# GitHub action to verify if our app build

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
       
    - name: npm ci (Backend)
      run: |
        cd Backend
        npm ci

    - name: npm ci & build (Frontend)
      run: |
        cd Frontend
        npm ci
        npm run build
